hlxsites/adobe-gmo

scripts/adobe-data-layer.js

Share one asset
Share multiple assets
Test Link
https://assets-31192--adobe-gmo--hlxsites.hlx.page/

ASSETS-31192 : Add Share Link to the Adobe Data Layer

---

scripts/adobe-data-layer.js

Added page-view to Adobe Data Layer
Test URL
https://ASSETS-31365--adobe-gmo--hlxsites.hlx.page
Screen Shots of page-view in the adobeDataLayer
Collections Page
Home Page
FAQ Page

ASSETS-31365 : Add page-view to Adobe Data Layer

---

scripts/adobe-data-layer.js

Added Collection Events  CREATE_COLLECTION, ADD_TO_COLLECTION, DELETE…_FROM_COLLECTION & DELETE_COLLECTION to Adobe Data Layer.
Test URL
https://ASSETS-31422--adobe-gmo--hlxsites.hlx.page
Screen Shot of Create Collection Adobe Data Layer
Screen Shot of Add To Collection Adobe Data Layer
Screen Shot of Delete From Collection Adobe Data Layer
Screen Shot of Delete Collection Adobe Data Layer

ASSETS-31422 : Add Collection Events to Adobe Data Layer

---

styles/gmo-styles.css

JIRA: [ASSETS-32297](https://jira.corp.adobe.com/browse/ASSETS-32297)
Test URLs:
- Before: https://main--adobe-gmo--hlxsites.hlx.page/qa/faq
- After: https://assets-32297--adobe-gmo--hlxsites.hlx.page/qa/faq

Assets 32297

---

blocks/adp-metrics/adp-metrics.js

JIRA: ASSETS-32307
Test URLs:
- Before: https://main--adobe-gmo--hlxsites.hlx.live/asset-metrics
- After: https://ASSETS-32307--adobe-gmo--hlxsites.hlx.live/asset-metrics

Updating Insights

---

contenthub/hydration/hydration.js

Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/browse/DXI-23344) your PR is for, as well as a description of your changes:
JIRA: DXI-23344
Test URLs:
- Before: https://chdemo--adobe-gmo--adobe.hlx.page/qa/
- After: https://DXI-23344--adobe-gmo--adobe.hlx.page/qa/

Commented out ProductFamily from 'Add Asset'

---

blocks/adp-header/adp-header.css
contenthub/hydration/hydration.js

https://jira.corp.adobe.com/browse/DXI-23343
https://jira.corp.adobe.com/browse/DXI-23342
https://jira.corp.adobe.com/browse/DXI-23782
Disabled Button when fields aren't filled.
Changed license behaviour.
Changed campaign/program behaviour.

DXI-23343: New Multi-required fields. Enable upload on form filled

---

contenthub/hydration/hydration.js

https://jira.corp.adobe.com/browse/DXI-23346

DXI-23346: Hydration uses values from Algolia for selections

---

contenthub/hydration/hydration.js

JIRA: [DXI-24743](https://jira.corp.adobe.com/browse/DXI-24743)
Test URLs:
- Before: https://main--assets-distribution-portal--adobe.hlx.page
Due to the type of change, it needs to be from a branch white listed on aem.
- After: https://chdemo--adobe-gmo--hlxsites.hlx.page/qa/assets

Changed folder for uploaded assets

---

contenthub/hydration/hydration-utils.js

MH: Added Firefly  product to AA Modal 'Product' Field List
JIRA: https://jira.corp.adobe.com/browse/DXI-24835
Test URLs: Tested it on https://localhost.corp.adobe.com/qa/assets since remote branch is not whitelisted. 
Preview of the changes:

updated hydration-utils.js

---

blocks/gmo-campaign-header/gmo-campaign-header.css
blocks/gmo-campaign-header/gmo-campaign-header.js

Campaign list header/filter component. Visual functionality is pretty much all there.
My drafts folder has a document set up with the necessary block, 'gmo-campaign-header' (/drafts/mdickson/campaigns).
Test URLs:
- Before: https://main--assets-distribution-portal--adobe.hlx.page/qa/assets
- After: https://assets-98991--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/campaigns

Campaign List filters display

---

blocks/adp-header/adp-header.js
scripts/security.js
scripts/site-config.js

Workfront Task 
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/661872a00092e28ffa289dec9fd941c1/overview
Test URLs:
Collection
https://assets-88899--adobe-gmo--hlxsites.hlx.page/qa/collection/urn_cid_aem_efbf273e-8058-4edc-81d3-f7180907f743
Share
https://assets-88899--adobe-gmo--hlxsites.hlx.page/qa/share/8d188116-c8d3-4c6c-8ba8-41bf7bd38329
**Authoring**
Edited the file sites/adobe-gmo/assets-distribution-portal/qa/site-config.xlsx
Work sheet share-quicklinks to

ASSETS-88899 : [Issue] Collection Detail Page is Redirecting to No-Access Page

---

contenthub/hydration/hydration-utils.js

JIRA: [DXI-24694](https://jira.corp.adobe.com/browse/DXI-24694)
Campaign and Program now allow custom values as well as the ability to search for existing values, or use the field as a select.

Added custom values for campaign and program

---

blocks/gmo-campaign-details/gmo-campaign-details.css
blocks/gmo-campaign-details/gmo-campaign-details.js
icons/Express.svg
icons/collapse.svg
icons/trophy.svg

Start implementing campaign details. The 'overview' tab and 'deliverables' tabs are basically done. Still need to implement tab-switching functionality.
- After: https://assets-98992--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/campaign-details

Assets 98992- Campaign details/overview

---

scripts/metadata.js

Added mapping for uuid so it can be used in site-config.xlsx
JIRA: DXI-25955
Test URLs:
- Before: https://marketinghub.adobe.com/qa/assets
- After: https://dxi-25955--adobe-gmo--hlxsites.hlx.page/qa/assets

Added mapping for uuid

---

blocks/gmo-campaign-header/gmo-campaign-header.js
blocks/gmo-campaign-list/gmo-campaign-list.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/6634172e001151b2345969983989ef70/overview
Note:
Only the Products and Status dropdown lists have been updated so far to use the updated graphql persisted queries
Test URLs:
https://assets-88902--adobe-gmo--hlxsites.hlx.page/drafts/tyrone/campaigns

ASSETS-88902 : Add Target Geo Filter in the Landing Page (update all dropdown lists to use updated graphql queries)

---

scripts/metadata.js

JIRA: [DXI-23766](https://jira.corp.adobe.com/browse/DXI-23766)
Test URLs:
- After: https://assets-35142--adobe-gmo--hlxsites.hlx.page/assets

Modified formatAssetMetadata() to allow custom dc-format Labels

---

blocks/gmo-campaign-list/gmo-campaign-list.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/6642590d00170e17147e04b93c3582cd/updates
Test URLs:
https://assets-88903--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard

ASSETS-88903 : [Issue] Product Name and Label are Undefined

---

blocks/gmo-campaign-details/gmo-campaign-details.css
blocks/gmo-campaign-details/gmo-campaign-details.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/663418520011ea9a5e8a0aae225f64c6/overview
Test URLs:
https://assets-88905--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=4/23%20Release:%20MAX%20London%20Ps%20+%20Id
https://assets-88905--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Best%20of%20YSYS

ASSETS-88905 : Add Fields to the Overview Tab

---

blocks/gmo-campaign-list/gmo-campaign-list.js

Added filtering to Previous and Next Buttons.
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/664e5ccb002cde5739df5a1c6a713959/overview
Test URLs:
https://assets-88906--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard#

ASSETS-88906 : Status and Product Filters not Showing Results

---

blocks/gmo-program-list/gmo-program-list.css
blocks/gmo-program-list/gmo-program-list.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/6658ec630053c7ccf14b55950e05524d/updates
Test URLs:
https://assets-88911--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard#

ASSETS-88911 : Tool Tip for Program Name & Marketing Moments

---

blocks/gmo-program-header/gmo-program-header.css
blocks/gmo-program-header/gmo-program-header.js
blocks/gmo-program-list/gmo-program-list.css
blocks/gmo-program-list/gmo-program-list.js
scripts/graphql.js

- improve thumbnail performance by making async
- format date property to yyyy-mm-dd
- fix margin issue in program header
- refactor function that builds header dropdown for increased performance
- make landing page (program-list) table header sticky
Test URLs:
- After: https://assets-98992--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/programs

Performance refactoring

---

blocks/gmo-program-details/gmo-program-details.js
blocks/gmo-program-list/gmo-program-list.js
scripts/graphql.js
scripts/shared-program.js

Update query names to match persisted query changes. Handle miscellaneous formatting issues.
See also: https://assets-98995--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=ASO%20FY24%20May%20Release%20Update&programID=65e6536a05191f07be8e4317af82f3dd
- After: https://assets-98995--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/programs

Update query names, handle formatting

---

blocks/gmo-program-list/gmo-program-list.js

https://assets-88915--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard

ASSETS-88915 : Fix Previous Page Pagination to go to the correct page

---

blocks/gmo-landing-page/gmo-landing-page.js

JIRA: https://jira.corp.adobe.com/browse/DXI-26587
-updated redirect condition in landing-page.js
-sharepoint changes to add redirect url: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD90917E5-7DCC-49AC-8A7B-D25AAAE25B1E%7D&file=index.docx&action=default&mobileredirect=true
Test Urls:
Before: https://main--adobe-gmo--hlxsites.hlx.page/qa/
After: https://dxi-26587--adobe-gmo--hlxsites.hlx.page/qa/

DXI-26587- Modify landing page for v3 Hub, so Signin goes to CH/v4

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js

Handle null values in query variables. Refactor header to show when no values are retrieved by getProgramDetails query.
- After: https://assets-98992--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=SEA%20Culturalised%20Intro%20&%20Regional%20Pricing&programID=664595c6001d64790f25ff7d16319d9e#

Refactor header and query variable extraction

---

blocks/gmo-program-details/gmo-program-details.css

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/666b6eaf008353fc8b049b85157d3a71/overview
Test URLs
Before
https://marketinghub.adobe.com/program-details?programName=Illustrator%20June%20Release&programID=662fed0d0289b3f642e78577cffc0dd4
After
https://assets-88919--adobe-gmo--hlxsites.hlx.page/program-details?programName=Illustrator%20June%20Release&programID=662fed0d0289b3f642e78577cffc0dd4

ASSETS-88919 : [Issue] Deliverables Page UI Breaking for Small Viewport

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js
blocks/gmo-program-list/gmo-program-list.css
blocks/gmo-program-list/gmo-program-list.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/666ca8c1004ce1eb6fa701e0b29dcbcc/updates
Test URLs:
https://assets-88920--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard
Add Geo column
https://assets-88920--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Acrobat%27s%20Got%20It&programID=6578983c049d6162a756ac83e90f3ccb
Program Details Updates

ASSETS-88920 : Cosmetic Updates from MVP Feedback

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js
blocks/gmo-program-list/gmo-program-list.css
blocks/gmo-program-list/gmo-program-list.js
scripts/assets.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/666b6fd4008412ed003bc943e4c157e5/overview
**Authoring**
Uploaded underdeveopment icon to /qa/logo/underdevelopment.svg
Updated site-config.xlsx worksheet shared-branding and added entry
underdevelopment-icon : logo/underdevelopment.svg
Test URLs:
Marketing Moments title is clickable
Gray thumbnail is replaced with 'Under Development' icon
https://assets-88921--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard
Rename "Review Link" to "QA Files" in the "Deliverable" task tab
https://assets-88921--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Adobe%20Express:%20Q3%20Run%20the%20Business&programID=6650eef505ebc8860981e6386f268d4d

ASSETS-88921 : Marketing Moments Clickable Title and Underdevelopment Icon for ProgramNames/Campaigns

---

blocks/gmo-program-header/gmo-program-header.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/667b0c1400255284eb4818f116fa7369/updates
Test URLs:
https://assets-88923--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard

ASSETS-88923 : Display MM Landing Filters Options in Alphabetical Order

---

blocks/gmo-program-details/gmo-program-details.js
scripts/assets.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/667ed4ec00604572052a29efd0f0652c/overview
Test URLs:
https://assets-88924--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard#
https://assets-88924--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=null&programID=

Add Placeholder Asset Preview Images on Program Details Page

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/6691598a001be1da00f7956b0f567793/overview
Test URLs:
- Before: https://marketinghub.adobe.com/program-details?programName=4/23%20Release:%20MAX%20London%20Ps%20+%20Id&programID=65d7e64d029a5bfffe1e807f346a0b5a#
- After: https://assets-88927--adobe-gmo--hlxsites.hlx.page/program-details?programName=4/23%20Release:%20MAX%20London%20Ps%20+%20Id&programID=65d7e64d029a5bfffe1e807f346a0b5a#

ASSETS-88927 : Toggle Read More Button

---

blocks/adp-header/adp-header.css
blocks/adp-header/adp-header.js
scripts/scripts.js
styles/styles.css

JIRA: DXI-27391
On the FAQ page only:
- Tabs are removed
- Link in the logo is controlled in Sharepoint
Test URLs:
- Before: https://marketinghub.adobe.com/qa/faq
- After: https://dxi-27391--adobe-gmo--hlxsites.hlx.page/qa/faq

Modified FAQ Nav

---

scripts/assets.js

Work Front Task : https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/66905052000b176b85bdb0da2b95fe16/overview
Updated existing function to
function searchAsset(programName, campaignName, deliverableType = '', imageWidth = 80)
Test URLs
Before 
https://rc--adobe-gmo--hlxsites.hlx.page/program-details?programName=Adobe%20Express:%20Q3%20Run%20the%20Business&programID=6650eef505ebc8860981e6386f268d4d
After
https://assets-88929--adobe-gmo--hlxsites.hlx.page/program-details?programName=Adobe%20Express:%20Q3%20Run%20the%20Business&programID=6650eef505ebc8860981e6386f268d4d

ASSETS-88929 : Create New Function and Query for Displaying Thumbnails in Calendar View

---

blocks/gmo-redirect/gmo-redirect.js
fstab.yaml

JIRA: https://jira.corp.adobe.com/browse/DXI-27620
Test URLs:
Before:
- https://marketinghub.adobe.com/asset-metrics
- https://marketinghub.adobe.com/collections
- https://marketinghub.adobe.com/qa/assets
- https://marketinghub.adobe.com/qa/collection/urn_cid_aem_9a54cb8b-fcd3-4ed6-8b43-881cfa1f949a
- https://marketinghub.adobe.com/qa/share/37db4d54-c38f-4089-a687-7573a5e1fdba
- https://marketinghub.adobe.com/qa/assets#assetId=urn:aaid:aem:510c22e9-6fd6-4e46-9f28-35413d472b6c
After: 
- https://dxi-27620--adobe-gmo--hlxsites.hlx.live/qa/asset-metrics
- https://dxi-27620--adobe-gmo--hlxsites.hlx.live/qa/collections
- https://dxi-27620--adobe-gmo--hlxsites.hlx.live/qa/assets
- https://dxi-27620--adobe-gmo--hlxsites.hlx.live/qa/collection/urn_cid_aem_9a54cb8b-fcd3-4ed6-8b43-881cfa1f949a
- …

Added redirect block which supports regex

---

blocks/gmo-program-details/gmo-program-details.css
scripts/program-calendar.js

Workfront Task: https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/66b2773e0033a3d9802335bc6241ca7d/updates?%3F_mr=https%3A%2F%2Fexperience.adobe.com%2Fassets%2Fruntime.c3dc2423.js&email-source=assignedToV2
Test URLs:
- Before: https://assets-72024--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Photoshop%20Gen%20Fill%20Fall%20Release%20Fast%20Follow&programID=651dafab01a6bd0a42d6c807d7cba3b8
- After: https://assets-72027--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Photoshop%20Gen%20Fill%20Fall%20Release%20Fast%20Follow&programID=651dafab01a6bd0a42d6c807d7cba3b8

ASSETS-72027 : [Issue] Fix Number Alignment on Calendar Page View

---

scripts/program-calendar.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/66be17d6000f95190a40d2c5a6d5017e/updates?%3F_mr=https%3A%2F%2Fexperience.adobe.com%2Fassets%2Fruntime.ae4a8e70.js&email-source=dueDateChanged
Test Links
Before
https://assets-72024--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Parent%20Brief%20%7C%20New%20HCV%20Fields&programID=66b27b53000210973416dedb277e01c3
After
https://assets-72029--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Parent%20Brief%20%7C%20New%20HCV%20Fields&programID=66b27b53000210973416dedb277e01c3

[Issue] Year View Navigator on Calendar Displays Extreme Years

---

blocks/gmo-program-header/gmo-program-header.css

JIRA: [ASSETS-00000](https://jira.corp.adobe.com/browse/DXI-27831)
Test URLs:
Marketing Dashboard:
- Before: https://marketinghub.adobe.com/marketing-dashboard
- After: https://localhost.corp.adobe.com/marketing-dashboard

DXI-27831: marketing dashboard filters fix

---

scripts/program-calendar.js

https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/66c61ef5003549912bffb989b626c52e/overview
Test URLs:
https://assets-72032--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=FY24Q1_AdobeExpress_Level%20Up&programID=6579eba106570b0510ff135fd863f823

HCV Pre-Release Refinements > Open QA Files links in a new tab in program calendar view

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js
scripts/assets.js

JIRA: https://jira.corp.adobe.com/browse/DXI-29263
- Fetching asset count based on Deliverable Type and Platform
- Both metadata types are now interactive buttons
- Displaying the total asset count upon click
Design Doc: 
- https://xd.adobe.com/view/4f7f6edd-3037-4902-8d37-b51e7a79b543-1a2c/screen/d33e1ab8-2c8f-4d7f-91a1-ccb13839a2b5?fullscreen
Test URLs:
- After: https://dxi-29263--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=ENV%20Update%20Test%20Campaign&programID=671a910f0005d2f623434630bf23c09f&path=/content/dam/gmo-cf/en/digital-media-dme/programs/env-update-test-campaign-671a910f0005d2f623434630bf23c09f

DXI- 29263

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js
scripts/shared-program.js

Display links to autocollections at the program and deliverable level.
Test URLs:
- After: https://assets-98981--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Product%20Launch%20X&programID=66fac0fa0023b3e06dc878516808b5ec&path=/content/dam/gmo-cf/en/digital-media-dme/programs/product-launch-x-66fac0fa0023b3e06dc878516808b5ec

Display autocollection info

---

blocks/gmo-program-header/gmo-program-header.js
blocks/gmo-program-list/gmo-program-list.js
scripts/graphql.js

JIRA: https://jira.corp.adobe.com/browse/DXI-30198
- Phase 1: Update the current search box to allow searching by Program Name, instead of Campaign Name.
Test Urls: 
Before: https://rc--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard
After: https://dxi-30198--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard

DXI- 30198

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js

- Refactor DOM element creation in the program-details block. 
- Update program-level collection display. 
- Fix bug in program-level collection JS that was showing incorrect names and incorrect links. 
- Fix bug in calendar display for programs with future start dates.
Test URLs:
- Before: https://marketinghub.adobe.com/program-details?programName=PerfMedia_ROI_Q1_Promo&programID=673e2bbe1c1de28ac8de7137cd89b47f&path=/content/dam/gmo-cf/en/digital-media-dme/programs/perfmedia-roi-q1-promo-673e2bbe1c1de28ac8de7137cd89b47f
- After: https://assets-98983--adobe-gmo--hlxsites.hlx.page/program-details?programName=PerfMedia_ROI_Q1_Promo&programID=673e2bbe1c1de28ac8de7137cd89b47f&path=/content/dam/gmo-cf/en/digital-media-dme/programs/perfmedia-roi-q1-promo-673e2bbe1c1de28ac8de7137cd89b47f

Assets 98983

---

blocks/gmo-program-details/gmo-program-details.css

CSS was nested incorrectly previously.
Test URLs:
- After: https://rc--adobe-gmo--hlxsites.hlx.page/marketing-dashboard

fix css nesting

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js
blocks/gmo-program-header/gmo-program-header.css
blocks/gmo-program-header/gmo-program-header.js

Add changes from pr#198 to new UAT branch. The changes were to add a new column for 'Task Status'.
Also, share link will now copy to clipboard with a 'copy to clipboard' button.
Test URLs:
- After: https://assets-91002--adobe-gmo--hlxsites.hlx.page/marketing-dashboard

Assets 91002

---

blocks/gmo-program-header/gmo-program-header.js
blocks/gmo-program-list/gmo-program-list.js
scripts/shared-program.js

Refactor saved search filters to use session storage, and also to clear after being retrieved.
Test URLs:
- After: https://assets-91000--adobe-gmo--hlxsites.hlx.page/marketing-dashboard

Refactor filter saving/sharing

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js
blocks/gmo-program-header/gmo-program-header.css
blocks/gmo-program-header/gmo-program-header.js
blocks/gmo-program-list/gmo-program-list.js
scripts/shared-program.js

1. Update the regex that parses URL params to exclude trailing # (so links from Slack should work).
2. Add "Copy to clipboard" button in share  link 
3. Add task Status column in deliverable view
4. Ability to share pre selected filters link 
Test URLs:
Before: https://main--assets-distribution-portal--adobe.hlx.page/sample-public-site
After: https://uat--adobe-gmo--hlxsites.hlx.page/program-details?programName=Spring%20into%202025&programID=67856e8e095fed692da5d17914e58eb7&path=/content/dam/gmo-cf/en/digital-media-dme/programs/spring-into-2025-67856e8e095fed692da5d17914e58eb7#

Release for 0320

---

blocks/gmo-program-details/gmo-program-details.css
blocks/gmo-program-details/gmo-program-details.js

Update 'task status' column for tasks in the deliverable list to be color-coded, similar to programs in the program list block. Also, resolve a bug with the 'status' tag for the program itself in the details block.
Test URLs:
- After: http://assets-91004--adobe-gmo--hlxsites.hlx.page/marketing-dashboard

fix program status, add task status style

---

blocks/gmo-program-header/gmo-program-header.js
blocks/gmo-program-list/gmo-program-list.js
scripts/shared-program.js

Refactor the MH blocks for cleaner DOM element creation.
Test URLs:
- After: https://assets-91006--adobe-gmo--hlxsites.hlx.page/marketing-dashboard

Refactor MH blocks for cleaner domEl creation
