scripts/adobe-data-layer.js
Added the  Event Listeners for the following new Events
ASSET_SELECTED: 'asset-selected'
ASSET_DESELECTED: 'asset-deselected'
ADD_ITEM_MULTISELECT: 'add-item-multiselect'
PREVIOUS_ASSET: 'previous-asset'
NEXT_ASSET: 'next-asset'
SEARCH_RESULTS_CHANGED: 'search-results-changed'
SESSION_STARTED: 'session-started'
ASSET_QUICK_PREVIEW_CLOSE: 'asset-quick-preview-close'
CLOSE_BANNER: 'close-banner'
URL for testing:
- https://assets-30051--adobe-gmo--hlxsites.hlx.page/
Screen shot of the new events in the Adobe Data Layer
=> Added the  Event Listeners for the following new Events

scripts/adobe-data-layer.js
Removed the Event Listener EventNames.INFINATE_SCROLL from the Adobe Data Layer
Test URL
https://assets-30051--adobe-gmo--hlxsites.hlx.page/#
Screen shot of the adobeDataLayer after the user has scrolled down all the assets.
The adobeDataLayer now does not show the event : infinite-scroll
=> Removed event  EventNames.INFINITE_SCROLL from the Adobe Data Layer

blocks/gmo-footer/gmo-footer.css, blocks/gmo-footer/gmo-footer.js, blocks/gmo-landing-page/gmo-landing-page.css, blocks/gmo-landing-page/gmo-landing-page.js, blocks/gmo-teaser/gmo-teaser.css, blocks/gmo-teaser/gmo-teaser.js, scripts/scripts.js, styles/gmo-styles.css, tools/sidekick/config.json
Added three new blocks:
1. gmo-landing-page
2. gmo-teaser
3. gmo-footer
Also added a metadata property "hide-header" (and updated scripts.js header-loading logic) that allows us to implement a page without the adp header.
When assembled in a document they can replicate the landing page from the AEM Sites version of Marketing Hub/GenStudio.
Styling includes mobile breakpoints for adjusting font size/layout/the video that appears in the page background.
URL for testing:
- https://assets-31139--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/landing-page
=> Assets 31139 - Landing page

styles/gmo-styles.css
Link to branch: https://assets-00000--adobe-gmo--hlxsites.hlx.live/qa/
When changing the logo, the image was too small.
Changed css height to have the image be taller, but not exceed the parent element's box.
=> Changed logo and modified css for the new size.

head.html, scripts/custom-scripts.js, styles/gmo-styles.css
- new branch
- small change to immutable(?) head.html
- 'custom-scripts.js' file with functions to enable the legal banner
Authors can add a 'legal-message' property to their branding config that controls the text of the toast message.
JIRA: ASSETS-32164
Test URLs:
https://assets-32164--adobe-gmo--hlxsites.hlx.page/sample-public-site
=> Assets 32164

blocks/adp-header/adp-header.js
JIRA: [ASSETS-32349](https://jira.corp.adobe.com/browse/ASSETS-32349)
Made changes to dynamically set the href of the adp-logo depending on whether the user is logged in and/or whether the user is navigating the /qa section of the site. 
A bug that prevented quick-links in /qa from being selected was also resolved.
Test URLs:
- Before: https://main--adobe-gmo--adobe.hlx.page/sample-public-site
- After: https://assets-32349--adobe-gmo--adobe.hlx.page/sample-public-site
=> Assets 32349

blocks/gmo-landing-page/gmo-landing-page.css, blocks/gmo-landing-page/gmo-landing-page.js, blocks/gmo-teaser/gmo-teaser.css
JIRA: [ASSETS-33680](https://jira.corp.adobe.com/browse/ASSETS-33680)
- Changes were made to the CSS styling of links found in teasers as the previous colors did not conform to accessibility requirements
- Changes were made to the CSS styling of links found on the landing page that are found withing paragraph elements (to avoid changing the "sign in" button) as the previous colors did not conform to accessibility requirements
- Code was added to the landing page that allows for the detection of the video background color, and also allows for changing the landing page link colors dynamically based on the video background.
- The video color detection only takes place for desktop, as for mobile users, links do not have a video background. 
Test URLs:
- Before: …
=> Assets 33680

blocks/adp-header/adp-header.js, scripts/security-imslib.js, scripts/security.js
JIRA: [ASSETS-34038](https://jira.corp.adobe.com/browse/ASSETS-34038)
- Made changes to checkUserAccess() that will allow login status to be checked even on pages where isPublicPage() is true
- Changed client_id to use imsLibConfig in case sharepoint is used for this purpose in the future
- Changes to getBearerTokenFromIMS() made so that window.adobeIMS.reAuthenticate() only runs on non public pages
- Simplified method of changing the adp-logo href using the ability to check user logged in status
- Header now loads quicklinks, searchfield and userinfo based on user login status, allowing quicklinks and userinfo to appear on public pages if logged in.
Test URLs:
- Before: https://main--adobe-gmo--hlxsites.hlx.page/sample-public-site
- After: …
=> Assets 34038

blocks/gmo-metrics/gmo-metrics.css, blocks/gmo-metrics/gmo-metrics.js
JIRA: DXI-23214
- Updated `gmo-metrics.js` and `gmo-metrics.css `
- Created 'Updated' property in `[adobe-gmo sharepoint](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BBCDE6939-EF40-4715-A556-07B0FBC2DFB8%7D&file=asset-metrics.docx&action=default&mobileredirect=true)` for easier content update in the future
- Created another asset story for preview server url which has not been set up for DXI yet
Test URLs:
- Before: https://main--adobe-gmo--hlxsites.hlx.page/
- After: https://assets-34569--adobe-gmo--hlxsites.hlx.page/asset-metrics
=> Assets 34569

blocks/adp-header/adp-header.css, contenthub/hydration/hydration.css, contenthub/hydration/hydration.js
JIRA: [DXI-23995 ](https://jira.corp.adobe.com/browse/DXI-23995)
- Changed text in modal.
- Added cancel button.
- Buttons behaviour changes after submit. Upload becomes Upload More. Cancel becomes done.
- On upload, hide form and show a lovely picture.
=> Updated Asset Upload Experience

blocks/adp-assets-actions/adp-assets-actions.js, blocks/adp-header/adp-header.js, scripts/security.js
JIRA: [ASSETS-35859](https://jira.corp.adobe.com/browse/ASSETS-35859)
Added the ability to hide the 'Add Assets' button in the quick-links based by comparing the users IMS groups to the 'imsAuthorGroup' value in the 'admin-config.xlsx' file in sharepoint.
Test URLs:
Before: https://main--adobe-gmo--hlxsites.hlx.page/
After: https://assets-35859--adobe-gmo--hlxsites.hlx.page/
=> 'Add Assets' button can now be hidden by IMS group

blocks/adp-asset-details-modal/adp-asset-details-modal.js, blocks/adp-asset-details-panel/adp-asset-details-panel.js, scripts/metadata.js
No Jira Ticket has been created for this task
Here is the Workfront Ticket
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/65e91385006b5c560e697b94fb0cfd81/overview
For Content that is not licensed
Test URLs: Before
Not licensed content display Adobe Express button
https://main--adobe-gmo--hlxsites.hlx.page/assets#assetId=urn:aaid:aem:efa25f56-5906-40c4-a994-0b4e7eff504a
Test URLs: After
https://assets-88890--adobe-gmo--hlxsites.hlx.page/assets#assetId=urn:aaid:aem:efa25f56-5906-40c4-a994-0b4e7eff504a
The Adobe Express button is shown
For Content that is licensed
Test URLs : Before (The express button is shown)
https://main--adobe-gmo--hlxsites.hlx.page/assets#assetId=urn:aaid:aem:1a7925ac-7ca4-4cb3-958c-09e64e2ee9f1
Test URLs: After (The express button is …
=> ASSETS-88890 : Hide "Edit in Express" icon for Licensed Content

blocks/adp-infinite-results-collections/CollectionsDatasource.js
Fixed the Collections Container to show the correct number of Collections
the bug was showing some collections twice.
Test URLs:
Before: https://main--adobe-gmo--hlxsites.hlx.page/qa/collections
After: https://assets-88892--adobe-gmo--hlxsites.hlx.page/qa/collections
=> ASSETS-88892 : Fixed Collection Card List

scripts/security.js, scripts/site-config.js
Workfront Task : [Show HCV report pages to limited users](https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/65fde8cc0005041153f21aaf938218de/updates)
Test URLs:
Before: https://main--assets-distribution-portal--adobe.hlx.page
After: https://assets-88895--adobe-gmo--hlxsites.hlx.page/drafts/tyrone/assets
**Authoring**
Created page /sites/HelixProjects/Shared Documents/sites/adobe-gmo/asset-distribution-portal/drafts/tyrone/marketing-dashboard.docx
with metadata
Updated config file /sites/HelixProjects/Shared Documents/sites/adobe-gmo/asset-distribution-portal/drafts/tyrone/admin-config.xlsx
Added new row
imsReportingGroup : IMS-QA-HCV-Reporting-group
Updated config file /sites/HelixProjects/Shared Documents/sites/adobe-gmo/asset-distribution-portal/drafts/tyrone …
=> ASSETS-88895 : Show HCV report pages to limited users

contenthub/hydration/hydration-utils.js
JIRA: 
https://jira.corp.adobe.com/browse/DXI-24690
https://jira.corp.adobe.com/browse/DXI-24691
=> MH: Add 'Asset Owner' Field to Add Assets Modal

scripts/graphql.js
Workfront Task https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/6616e66d00c91821c574e5a2d790c1bf/overview
(Backend) Campaign Overview Page Components
Added function export async function graphqlFilterOnMarketingInitiative(marketingInitiative) to scripts/graphql.js
Which calls the persisted query gmo/filter-on-marketing-initiative with example parameters
{
"marketingInitiative": "FY24Q1-Q2_AdobeExpress_level Up"
}
https://author-p108396-e1046543.adobeaemcloud.com/graphql/execute.json/gmo/filter-on-marketing-initiative%3BmarketingInitiative=FY24Q1-Q2_AdobeExpress_level%20Up
Example JavaScript code on how to call it from block component
```
import { graphqlFilterOnMarketingInitiative } from '../../scripts/graphql.js';
..
const marketingIntiative = await …
```
=> ASSETS-88898 : (Backend) Campaign Overview Page Components

blocks/gmo-campaign-header/gmo-campaign-header.css, blocks/gmo-campaign-header/gmo-campaign-header.js, blocks/gmo-campaign-list/gmo-campaign-list.js, scripts/graphql.js
Workfront Task :  https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/team/64120499002edcb6e4ef1dbc3e644241/iterations
Test URLs: https://assets-88901--adobe-gmo--hlxsites.hlx.page/drafts/tyrone/campaigns#
AEM GraphQL Persisted Queries Created/Used
Used for Campaign List
https://author-p108396-e1046543.adobeaemcloud.com/graphql/execute.json/gmo/getAllCampaigns;first=;cursor=;filter=
Used for Campaign total records count
https://author-p108396-e1046543.adobeaemcloud.com/graphql/execute.json/gmo/getCampaignNameFilter;filter=
Used for Campaign Name search auto complete list
https://author-p108396-e1046543.adobeaemcloud.com/graphql/execute.json/gmo/getCampaignNames;campaignName=
=> ASSETS-88901 : (Backend) Campaign Page: Filters

scripts/metadata-html-builder.js
JIRA: [DXI-25955](https://jira.corp.adobe.com/browse/DXI-25955)
Made changes to the Metadata HTML Builder in order to remove the  "urn:aaid:aem:" prefix from the "assetId" displayed value in the assets detail side panel and modal without breaking other functionality dependent on "assetId". 
Test URLs:
- Before: https://marketinghub.adobe.com/qa/assets
- After: https://dxi-25955-ch--adobe-gmo--hlxsites.hlx.page/qa/assets
=> Removed Prefix from Displayed UUID Value on Assets

blocks/gmo-campaign-details/gmo-campaign-details.js, blocks/gmo-campaign-list/gmo-campaign-list.js
Make links to/from the list and details blocks configurable.
On the `gmo-campaign-list` block document, add a property called `detailsPage` and supply the name of the document that has the `gmo-campaign-details` block.
Similarly, on the `gmo-campaign-details` block document, add a property called `listPage` and give the name of the document with the `gmo-campaign-list` block.
- After: https://assets-98995--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/campaigns
=> make links configurable, remove extraneous logs

blocks/gmo-campaign-details/gmo-campaign-details.css, blocks/gmo-campaign-details/gmo-campaign-details.js, blocks/gmo-campaign-header/gmo-campaign-header.js, blocks/gmo-campaign-list/AssetsDatasource.js, blocks/gmo-campaign-list/gmo-campaign-list.js, scripts/assets.js, scripts/scripts.js
Workfront Task : https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/663cf46b002751876d8e92b9a31b048f/overview
Test URLs:
https://assets-88904--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard
Authoring program-details.docx page
Added the following metadata
listPage : marketing-dashboard
=> ASSETS-88904 : Update Asset Thumbnail for Campaign List Entries

contenthub/hydration/hydration-utils.js
JIRA: DXI-26290
Test URLs:
Add asset modal only appears on specific branches and local. No test URL available.
Removed the ability to add custom values to tag fields.
Removed Campaign/Program from both being required or not required. They are now both optional.
=> Removed "required" and custom values for fields

blocks/adp-collection-header/adp-collection-header.js
JIRA: [DXI-26385](https://jira.corp.adobe.com/browse/DXI-26385)
This change will make sure that users in the QA environment will be sent to the proper environment when using the back button in the collections header.
Test URLs:
- After: https://assets-39177--adobe-gmo--hlxsites.hlx.page/assets
=> Added getBaseConfigPath to Collections Back Button

blocks/gmo-campaign-details/gmo-campaign-details.js, scripts/shared-mappings.js
Add graphql label mapping for 'platform' property on the campaign list and campaign details blocks.
Also cleaned up commented-out code from previous PR.
- After: https://assets-98997--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/campaign-details?programName=4/23%20Release:%20MAX%20London%20Ps%20+%20Id
=> platforms mapping with graphql

blocks/gmo-program-header/gmo-program-header.js
**Close Filter Drop-downs when User Selects Option**
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/664e5cfa002cf7a698094b3d11f54444/updates
The Dropdown Filters are closed, when the user clicks Reset Filters or clicks outside of the Drop Down lists.
Also fixed bug when Reset Filters button is selected, the Product Dropdown list is empty.
Now the Product List is repopulated with All the products, when the Reset Filters button is clicked.
Test URLs: https://assets-88910--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard#
=> ASSETS-88910 : Close Filter Drop-downs when User Selects Option

blocks/gmo-program-details/gmo-program-details.js, blocks/gmo-program-list/gmo-program-list.js
Update queries to use 'programID' instead of 'programReferenceNumber'.
- After: https://assets-98993--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=FY24%20Q1_Feature%20Marketing&programID=6568e63001f3b37dc342a6c17cda32c3
=> add programID parameter to deliverable query

blocks/gmo-program-list/gmo-program-list.js
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/665a5f27001d948c24555407f12b11ce/updates
Test URLs:
https://assets-88914--adobe-gmo--hlxsites.hlx.page/qa/marketing-dashboard#
=> ASSETS-88914 : Fix Pagination Frontend Code

scripts/polaris.js
Replaced throwing 404 error when the asset is not found, with asset icon
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/6668691100211267b48729347cc39bd9/overview
Test URLs:
Before
https://rc--adobe-gmo--hlxsites.hlx.page/program-details?programName=Acrobat%27s%20Got%20It&programID=6578983c049d6162a756ac83e90f3ccb
After
https://assets-88917--adobe-gmo--hlxsites.hlx.page/program-details?programName=Acrobat%27s%20Got%20It&programID=6578983c049d6162a756ac83e90f3ccb
https://assets-88917
=> ASSETS-88917: [Issue] 404 Error on Getting Total Asset Count

blocks/gmo-program-details/gmo-program-details.js, blocks/gmo-program-header/gmo-program-header.js, blocks/gmo-program-list/gmo-program-list.js, scripts/graphql.js, scripts/shared-program.js, scripts/site-config.js
Allow authors to provide mappings for the paths to content fragments that we use to derive friendly labels for Workfront values.
- After: https://assets-98991--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/programs
=> Make content fragment path for WF mappings configurable

scripts/security.js
JIRA: DXI-26839
Test URLs: https://dxi-26839--adobe-gmo--hlxsites.hlx.page/qa/assets
New users do not have a profile picture yet. fetchCached apparently will halt instead of returning undefined.
=> Fixed issue where header didn't load if the user didn't have a profile picture yet

blocks/gmo-program-details/gmo-program-details.js
Fix issue where deliverables are showing invalid 'Review Links' when the reviewLink property is not populated. Also refactored the 'Final Asset' logic to use the same.
- After: https://assets-98992--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=Express_Express%20for%20Business%20Launch&programID=66466a56027b70c2ee6edd2f027cc68a
=> add checks for null 'review link' and 'final asset'

blocks/gmo-program-header/gmo-program-header.js
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/666a109a005068cb816b843c137f225e/overview
Test URLs:
https://assets-88918--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> ASSETS-88918 : [Issue] Reset Filters button is not working intermittently

blocks/gmo-program-details/gmo-program-details.js
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/667989760012480d95a17371e37dfede/overview
Test URLs:
Before
https://rc--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Express_Express%20for%20Business%20Launch&programID=66466a56027b70c2ee6edd2f027cc68a
After
https://assets-88922--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Express_Express%20for%20Business%20Launch&programID=66466a56027b70c2ee6edd2f027cc68a
=> ASSETS-88922 : Review the Deliverable page load time

blocks/gmo-program-list/gmo-program-list.js
Improved changes
Implement debounce for search input to reduce the number of API calls.
Refactor the decorate function for better readability and performance.
Add lazy loading for images using IntersectionObserver to load images only when they come into view.
Move pagination button toggling to a separate togglePaginationButtons function.
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/668c190a002545eb036d1a66018bd8db/overview
Test URLs:
Before: https://marketinghub.adobe.com/marketing-dashboard
After: https://assets-88926--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> ASSETS-88926 : Review and Improve Page Performance of Marketing Moment Landing page

blocks/gmo-program-list/gmo-program-list.js
Improved changes
Add lazy loading for images using IntersectionObserver to load images only when they come into view.
Move the pagination button toggling to a separate togglePaginationButtons function.
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/668c190a002545eb036d1a66018bd8db/overview
Test URLs:
Before: https://marketinghub.adobe.com/marketing-dashboard
After: https://assets-88926--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> ASSETS-88926 : Review and Improve Page Performance of Marketing Moment Landing page (Push Failed)

scripts/program-calendar.js
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/669e7376000bcb720f2ab0c99252f216/overview
Test URLs:
- Before: https://assets-72024--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=Illustrator%20June%20Release&programID=662fed0d0289b3f642e78577cffc0dd4
- After:  https://assets-72026--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=Illustrator%20June%20Release&programID=662fed0d0289b3f642e78577cffc0dd4
Authoring
Edited file drafts/mdickson/sites-config.xlsx file worksheet shared-query-fragments
Has the new entry
mapping-Type    path
taskStatus.           /content/dam/gmo-cf/en/wf-picklist-data-source/taskStatus
=> ASSETS-72026 : Use taskStatus CF for mapping to get the task status label

blocks/gmo-program-details/gmo-program-details.css, blocks/gmo-program-details/gmo-program-details.js, scripts/program-calendar.js
- update start/end date properties
- change tooltip on 'end date' pill
- update filter to show current view
- disable increment/decrement if no add'l years to show
- After: https://assets-98992--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=Adobe%20Express:%20A.com%20Run%20the%20Business&programID=655509ff01fbe3b675abb4bc5098183c
=> Assets 98992

blocks/gmo-program-details/gmo-program-details.css, blocks/gmo-program-details/gmo-program-details.js
WF Task
https://experience.adobe.com/#/@wfadoberm/so:adoberm-Production/workfront/task/66b6328d000cba739fb7fda1babe537f/overview
Test URLs:
https://assets-72028--adobe-gmo--hlxsites.hlx.page/qa/program-details?programName=Parent%20Brief%20%7C%20New%20HCV%20Fields&programID=66b27b53000210973416dedb277e01c3
=> Update on CF and GraphQL Rename field categories to productGroup

blocks/gmo-program-details/gmo-program-details.css, scripts/program-calendar.js
Add a message to the calendar tab that indicates there are no deliverables to be shown.
- After: https://assets-98992--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=MPgM%20Training%20Request%20-%20Demo&programID=66731b7e0ac4b41af639322d597ece3d
=> display msg when no deliverables in calendar

blocks/gmo-program-details/gmo-program-details.js, scripts/program-calendar.js
- main js for details block now programmatically retrieves current year
- updated missing data msg for calendar view
- After: https://assets-72090--adobe-gmo--hlxsites.hlx.page/program-details?programName=Summit%202025%20CSC%20Project&programID=66aa945b075a9e4cc04e149f1d72fb8c#
=> use current year in initial block, update msg

blocks/gmo-program-details/gmo-program-details.css
Setting a max-height skews the aspect ratio and sometimes shows the gray default background. With overflow: hidden you can still get an idea of what the thumbnail is without having it look distorted.
- After: https://assets-72091--adobe-gmo--hlxsites.hlx.page/program-details?programName=Stock%20Q3%20Influencers&programID=66aa82c402e3be87aa22c972cd8187d7#
=> Fix calendar task thumbnails

blocks/gmo-program-details/gmo-program-details.js
Simple fix, update variable name. Also deleted commented code.
- After: https://assets-72093--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=4/23%20Release:%20MAX%20London%20Ps%20+%20Id&programID=65d7e64d029a5bfffe1e807f346a0b5a
=> fix bug by updating variable name. delete comment

blocks/gmo-program-details/gmo-program-details.js
Change remaining validity checks to be timezone-agnostic.
- After: https://assets-72094--adobe-gmo--hlxsites.hlx.page/drafts/mdickson/program-details?programName=4/23%20Release:%20MAX%20London%20Ps%20+%20Id&programID=65d7e64d029a5bfffe1e807f346a0b5a
=> Fix date validity checks

blocks/gmo-program-details/gmo-program-details.css, blocks/gmo-program-details/gmo-program-details.js
- Adjust min width on group headings in calendar view
- Fix logic for assigning colors to groups in calendar view (cyan shouldn't show up, counter properly resets)
Test URLs:
- After: https://assets-72096--adobe-gmo--hlxsites.hlx.page/program-details?programName=Adobe%20Express:%20Q3%20Run%20the%20Business&programID=6650eef505ebc8860981e6386f268d4d&path=/content/dam/gmo-cf/en/digital-media-dme/programs/adobe-express-q3-run-the-business-6650eef505ebc8860981e6386f268d4d
=> Visual bugfixes for calendar view

blocks/gmo-program-details/gmo-program-details.css, blocks/gmo-program-details/gmo-program-details.js
Per feedback received during HCV dashboard demo, add the ability to hide the calendar tab.
To do this, add a line to the table in the `program-details.docx` doc called "hideCalendar" with value "true" or "false". Example:
Test URLs:
- Before: https://rc--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
- After: https://assets-98986--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> Add ability to hide calendar tab via block config

blocks/gmo-program-details/gmo-program-details.css, blocks/gmo-program-details/gmo-program-details.js
Per feedback received during HCV dashboard demo, add the ability to hide the calendar tab.
To do this, add a line to the table in the program-details.docx doc called "hideCalendar" with value "true" or "false". Example:
image
Test URLs:
Before: https://main--assets-distribution-portal--adobe.hlx.page/sample-public-site
After: https://rc--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> cherrypick calendar tab changes

blocks/gmo-program-details/gmo-program-details.js
Update the regex that parses URL params to exclude trailing # (so links from Slack should work).
Test URLs:
- After: https://assets-98988--adobe-gmo--hlxsites.hlx.page/program-details?programName=February%20L1%20Release_iPhone%20App%20GA&programID=667087ec00be4054816fbf84c5f104ce&path=/content/dam/gmo-cf/en/digital-media-dme/programs/september-l0-release-iphone-app-ga-667087ec00be4054816fbf84c5f104ce#
=> ensure path capture group stops at #

blocks/gmo-program-details/gmo-program-details.js
Update the regex that parses URL params to exclude trailing # (so links from Slack should work).
Test URLs:
Before: https://main--assets-distribution-portal--adobe.hlx.page/sample-public-site
After: https://assets-98989--adobe-gmo--hlxsites.hlx.page/program-details?programName=February%20L1%20Release_iPhone%20App%20GA&programID=667087ec00be4054816fbf84c5f104ce&path=/content/dam/gmo-cf/en/digital-media-dme/programs/september-l0-release-iphone-app-ga-667087ec00be4054816fbf84c5f104ce#
=> update regex to exclude trailing # in capture group

blocks/gmo-program-details/gmo-program-details.js, blocks/gmo-program-header/gmo-program-header.css, blocks/gmo-program-header/gmo-program-header.js, blocks/gmo-program-list/gmo-program-list.js, scripts/shared-program.js
Add changes from pr#192 and pr#193 to the new UAT branch as they were never merged to main. They include the 'back' button in program details page re-applying your existing filters (if they exist) and the ability to share your current filter with another user.
Test URLs:
- After: https://assets-91000--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> Merge back button and link sharing enhancements

blocks/gmo-program-list/gmo-program-list.js
Address a bug where pagination buttons were being referenced before the DOM finished loading
Test URLs:
- After: http://assets-91001--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> refactor prev/next btn activation

blocks/gmo-program-list/gmo-program-list.js
Solve race condition in processing filters where function would occasionally run before the DOM elements it referenced would finish loading
Test URLs:
- After: https://assets-91003--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> defer filters processing

blocks/gmo-program-list/gmo-program-list.js, scripts/graphql.js
Update the filters in the program list to make use of the new 'projectUse' parameter, and to filter programs that are marked as 'test' and 'demo' from the dashboard.
Test URLs:
- After: https://assets-91005--adobe-gmo--hlxsites.hlx.page/marketing-dashboard
=> Filter programs flagged as 'test' or 'demo'
